version: "3.5"

services:
  php_fpm:
      build: .
      container_name: mvc_template_php_fpm
      working_dir: /app
      volumes:
          - ./:/app

  nginx:
      image: nginx:1.15
      container_name: mvc_template_nginx
      working_dir: /app
      ports:
          - "8080:80"
      volumes:
          - ./:/app
          - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
